Adding a page to demo the "Solo" one stage tag
socialvibe/truex-android-mobile-reference-app pull request #18
Opened 2021-10-01 20:27 UTC by kylelamx

This PR is to add support/ showcase the one-stage approach.
As well as updating the existing UI.

Jira: https://truextech.atlassian.net/browse/CTV-3219

![Screenshot_20211001-132409](https://user-images.githubusercontent.com/36866533/135682355-047eb337-ad1c-46c9-899d-42b4b7e54750.png)

![Screenshot_20211001-132416](https://user-images.githubusercontent.com/36866533/135682361-8b2e3fe8-b50e-4632-bc03-83d3c1e261bc.png)

2021-10-01 20:35 UTC, imann24 commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            toast("Not Ready-- Downloading VAST");
Is there a reason we can't just wait synchronously to start the creative?

2021-10-01 20:36 UTC, imann24 commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            // Just checking the 1st ad here to simplify the flow in this example
Don't we always assume the 1st ad is true[X].

2021-10-01 20:36 UTC, imann24 commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            toast("Already Unlocked");
Nice uses of `toast` function! 🍻

2021-10-01 20:37 UTC, imann24 commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            truexAdRenderer.destroy();
Should we add another comment that the renderer should NOT be reused?

2021-10-01 20:38 UTC, imann24 commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +    private IEventEmitter.IEventHandler adFetchCompleted = (TruexAdEvent event, Map<String, ?> data) -> {
Nice use of lambdas 👏

2021-10-01 20:39 UTC, imann24 commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +                    parser.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, false);
Curious what this is doing?

2021-10-01 20:40 UTC, imann24 commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +    private void toast(String message) {
Nice helper method!

2021-10-01 20:40 UTC, imann24 commented on ReferenceApp/src/main/res/layout/fragment_unlock.xml
> +    <!-- TODO: Update blank fragment layout -->
Is this is a TODO to be captured in Jira or to be fixed in this PR?

2021-10-01 20:41 UTC, imann24 approved these changes
Nice, looks good!

2021-10-01 22:18 UTC, kylelamx commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            // Just checking the 1st ad here to simplify the flow in this example
not in this use case. This is not FEP

2021-10-01 22:21 UTC, kylelamx commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            toast("Not Ready-- Downloading VAST");
There isn't a real reason. This fake ad manager is not part of the true[X] experience and I'm trying to simplify things here.

2021-10-01 22:21 UTC, kylelamx commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +                    parser.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, false);
I got that from Google's sample code and never actually know what it does.
https://developer.android.com/training/basics/network-ops/xml#instantiate

2021-10-01 22:21 UTC, kylelamx commented on ReferenceApp/src/main/res/layout/fragment_unlock.xml
> +    <!-- TODO: Update blank fragment layout -->
thanks! Android Studio hid that comment from me.

2021-10-04 16:18 UTC, addisonm commented
When I click on the solo/unlock, its a blank screen after showing a few toasts.  Does not sound intended.  
```

2021-10-04 09:17:12.354 5710-5710/com.truex.referenceapp I/chromium: [INFO:CONSOLE(1044)] "startAd", source: https://qa-media.truex.com/integration/fw_renderers/choicecard.js (1044)
2021-10-04 09:17:12.366 5710-5710/com.truex.referenceapp I/chromium: [INFO:CONSOLE(151)] "Uncaught TypeError: Cannot read property 'image_url' of undefined", source: https://qa-media.truex.com/integration/fw_renderers/choicecard.js (151)
```

2021-10-04 16:33 UTC, addisonm commented on ReferenceApp/src/main/res/layout/fragment_unlock.xml
> +            android:text='This page is meant to showcase the one stage "solo" tag. On page appear, we will try to download an ad from ad server. When click unlock with true[X] button above, the true[
Nitpicking the language here a bit since this is for clients and it sounds a bit off currently.  

"...When clicking unlock, the true[X] engagement will start..." 
"After the user finishes the ad"

Is all the terminology obvious to the customer here?

2021-10-04 16:41 UTC, addisonm commented on ReferenceApp/src/main/java/com/truex/referenceapp/detail/DetailFragment.java
> +    private void loadUnlockFragment() {
The code duplication is okay here.  But some consideration to making some of this code common for new fragments.

2021-10-04 16:45 UTC, addisonm commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            Map currentAd = (Map)((ArrayList)((Map)((ArrayList)vastMap.get("Ad")).get(0)).get("InLine")).get(0);
This looks disgusting, lol.  But unless getting setting up a library, a somewhat necessary evil.  I'll want to look at the payload if I have any better suggestions (but it seems my response might not be working)

2021-10-04 16:52 UTC, kylelamx commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            Map currentAd = (Map)((ArrayList)((Map)((ArrayList)vastMap.get("Ad")).get(0)).get("InLine")).get(0);
If only at least I don't have to do all the casting...

2021-10-04 16:53 UTC, addisonm commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            if (isTruexAd) {
I wonder if there is a way to make this common with the ad detection for the original ref app effort.  I simplified it by having a custom JSON, but this area is the same, except with a real XML payload.

2021-10-04 16:58 UTC, addisonm commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +    private void fetchAd(final String rawUrlString) {
Suggest this to be a more generic XML request helper, but I see a little bit of TrueX specific code inside as well.

2021-10-04 16:59 UTC, addisonm requested changes
Looks nice visually, better than what I had as placeholder.  Some nitpicks and general comments about the flow.  Is it only me where the ad doesn't actually work?  Didn't really look much further.  I was using emulator if that matters.

2021-10-04 17:40 UTC, kylelamx commented
> Looks nice visually, better than what I had as placeholder. Some nitpicks and general comments about the flow. Is it only me where the ad doesn't actually work? Didn't really look much further. I was using emulator if that matters.

It seems this also happens to the normal video flow when I have a poor network connection. Let me take a deeper look.

2021-10-04 17:57 UTC, kylelamx commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +    private void fetchAd(final String rawUrlString) {
I think the only part is we replace some macros, which aren't really true[X] macro either. I can move that code out to make it clearer.

2021-10-04 18:05 UTC, rblaa commented on ReferenceApp/src/main/java/com/truex/referenceapp/unlock/UnlockFragment.java
> +            Map currentAd = (Map)((ArrayList)((Map)((ArrayList)vastMap.get("Ad")).get(0)).get("InLine")).get(0);
This is java right? Use templated collections, then it all comes for free
E.g. ArrayList<Map<Integer,String>> someList = new ArrayList<>();

2021-10-04 22:23 UTC, kylelamx commented
> Looks nice visually, better than what I had as placeholder. Some nitpicks and general comments about the flow. Is it only me where the ad doesn't actually work? Didn't really look much further. I was using emulator if that matters.

I cannot reproduce this anymore, I created this ticket to take a deeper look at it. 
https://truextech.atlassian.net/browse/CTV-3226

Meanwhile, I will merge this current PR.

2021-10-04 22:23 UTC, merged

2021-10-05 22:36 UTC, addisonm commented
If its possible, some color on the button or state to make it clear.  It is hard to tell what happens when the user comes back from the ad.  The text changes, but its not obvious (to me).